"""auto

Revision ID: 00b9802a800e
Revises: 728082370bfb
Create Date: 2026-04-05 09:50:51.425202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b9802a800e'
down_revision: Union[str, None] = '728082370bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_game', sa.Column('is_finish', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_game', 'is_finish')
    # ### end Alembic commands ###
