"""auto

Revision ID: 0dbc2aa92510
Revises: 159a48b1e9b2
Create Date: 2026-04-04 18:32:10.546602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbc2aa92510'
down_revision: Union[str, None] = '159a48b1e9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_archive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_archive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
