"""auto

Revision ID: 1538c8fb22d1
Revises: 00b9802a800e
Create Date: 2026-04-05 15:25:35.617409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1538c8fb22d1'
down_revision: Union[str, None] = '00b9802a800e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_game', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('session_game', sa.Column('result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_game', 'result')
    op.drop_column('session_game', 'age')
    # ### end Alembic commands ###
