"""auto

Revision ID: 728082370bfb
Revises: dffaea112fbe
Create Date: 2026-04-05 09:30:56.044465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728082370bfb'
down_revision: Union[str, None] = 'dffaea112fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_game', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'session_game', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_game', type_='foreignkey')
    op.drop_column('session_game', 'user_id')
    # ### end Alembic commands ###
