"""auto

Revision ID: 8dd46aac22a3
Revises: 1538c8fb22d1
Create Date: 2026-04-05 16:18:23.769361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd46aac22a3'
down_revision: Union[str, None] = '1538c8fb22d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_game', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('session_game', 'name')
    op.drop_column('session_game', 'surname')
    op.drop_column('session_game', 'patronymic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_game', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('session_game', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('session_game', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('session_game', 'full_name')
    # ### end Alembic commands ###
