"""auto

Revision ID: d73a5ffeabbd
Revises: dc61e4a369b2
Create Date: 2026-04-06 13:40:23.111600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73a5ffeabbd'
down_revision: Union[str, None] = 'dc61e4a369b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_game', 'background',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_game', 'background',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
